### ISSUE TITLE
CUB200 dataset does not download automatically

### ISSUE THREAD

**Issue by francesco-p** [Continvvm/continuum#253]
# To reproduce

Just run your colab and replace MNIST with CUB200 and you get the error during the extraction of the tar file.

edit:
even by cloning the repo and pip installing it throws the error.

![image](https://user-images.githubusercontent.com/5663725/143064255-55485d3f-9cff-47cb-a0be-2f5a1156db1c.png)

**Comment by arthurdouillard** [comment]
Unfortunately, it seems that the quote of download for this dataset as exceed.

Here is the content of the downloaded file (which should have been a .tgz archive):

```
Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.
```

I cannot host by myself the file archive, and the official download page (http://www.vision.caltech.edu/visipedia/CUB-200.html) only gave this google drive link. So you may want to contact the author to tell them about that, because `continuum` cannot do anything about that I'm afraid.

**Comment by francesco-p** [comment]
looks like even with manual download it does not work. 
I just placed the correct .tgz (I downloaded it manually it is the correct 1.1GB file) 

![image](https://user-images.githubusercontent.com/5663725/143572249-5a128f75-ea4f-411d-8c90-609877481852.png)

**Comment by francesco-p** [comment]
OK, if you donwload it manually it works. Maybe you can specify this thing in the documentation. Thanks anyway.

**Comment by arthurdouillard** [comment]
I'll add a warning message in the code, because it SHOULD work automatically, but I guess a few times it won't.

**Comment by arthurdouillard** [comment]
Well I was able right now to download cub200 with continuum...

Anyway, I've added an error message in case this bug re-appears: https://github.com/Continvvm/continuum/commit/9c29d8a1e1f9f54eac51e10b2ed37571c517905d
