### ISSUE TITLE
Custom Transformation 

### ISSUE THREAD

**Issue by NiccoBiondi** [Continvvm/continuum#263]
Hi I'm currently using a custom transformation, which outputs a list of two elements, i.e. a batch has shape (BATCH, 2, 3, 112, 112) where BATCH is the batch size and each image has shape 3,112,112. 

I' m using the ArrayTaskSet but there is an issue with the **_prepare_data** function (https://github.com/Continvvm/continuum/blob/master/continuum/tasks/image_array_task_set.py)
```python
def _prepare_data(self, x, y, t):
    if self.trsf is not None:
        x = self.get_task_trsf(t)(x)
    if not isinstance(x, torch.Tensor):
        x = self._to_tensor(x)
    return x, y, t
```
In particular it fails the following statement when the result of the transformation is not a tensor
```python
if not isinstance(x, torch.Tensor):
    x = self._to_tensor(x)
```

Could you consider deleting this statement in order to allow this use?

best regards, 
Niccolò

**Comment by TLESORT** [comment]
Hi Niccolò,

Thanks for your issue.
This line is quite important ensure the return of data of  `torch.Tensor` type. So I don't think we can remove it.

However, something that could work for you is too create another class to overwrite `ArrayTaskSetBis` .

```
class ArrayTaskSetBis(ArrayTaskSet):
         def _prepare_data(self, x, y, t):
               return x, y, t
```
and to use this class instead of `ArrayTaskSet`.
However, I can not ensure it will not create other problems in continuum...

Or maybe you can share your custom transformation so we can try to find a solution to your problem :)
have a nice day
Timothée

**Comment by NiccoBiondi** [comment]
Hi Timothée, 
yeah I understand your point. 
The ArrayTaskSetBis was also my solution to overcome this issue. 

Thanks again. 
Niccolò
